### ISSUE TITLE
Stats are different from the paper

### ISSUE THREAD

**Issue by kornosk** [ucinlp/covid19-data#12]
Paper = 6761 (pos=670, neg=343, na=5748)
covid_lies.csv = 6591 (pos=288, neg=154, na=6149)

Could you please check the data file? Thank you~

**Comment by atleastbeth3** [comment]
Our paper used [v0.1](https://github.com/ucinlp/covid19-data/releases/tag/v0.1) of the dataset. The latest version is [v1.0 ](https://github.com/ucinlp/covid19-data/releases/tag/v1.0)(changes described in the release notes).
